#ifndef LIBAPPLICATIONLOGDB_GLOBAL_H
#define LIBAPPLICATIONLOGDB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBAPPLICATIONLOGDB_LIBRARY)
#  define LIBAPPLICATIONLOGDB_EXPORT Q_DECL_EXPORT
#else
#  define LIBAPPLICATIONLOGDB_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBAPPLICATIONLOGDB_GLOBAL_H
