#ifndef LIBAPPLICATIONSETTINGS_GLOBAL_H
#define LIBAPPLICATIONSETTINGS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBAPPLICATIONSETTINGS_LIBRARY)
#  define LIBAPPLICATIONSETTINGS_EXPORT Q_DECL_EXPORT
#else
#  define LIBAPPLICATIONSETTINGS_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBAPPLICATIONSETTINGS_GLOBAL_H
